name: atari_mpc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _x86_64-microarch-level=3=2_skylake
  - absl-py=2.1.0=pyhd8ed1ab_1
  - alsa-lib=1.2.13=hb9d3cd8_0
  - ampl-asl=1.0.0=h5888daf_2
  - aom=3.9.1=hac33072_0
  - archspec=0.2.5=pyhd8ed1ab_0
  - assimp=5.4.3=h8943939_0
  - attrs=24.3.0=pyh71513ae_0
  - beautifulsoup4=4.12.3=pyha770c72_1
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.18.2=h3394656_1
  - casadi=3.6.7=py312hc8887ff_3
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - chardet=5.2.0=py312h7900ff3_2
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - cli11=2.4.2=h5888daf_0
  - click=8.1.8=pyh707e725_0
  - coal=3.0.0=hd8ed1ab_5
  - coal-python=3.0.0=py312he880d2f_5
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.1.0=py312h7900ff3_0
  - conda-build=25.1.1=py312h7900ff3_2
  - conda-index=0.5.0=pyhd8ed1ab_0
  - conda-libmamba-solver=25.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - console_bridge=1.0.2=h924138e_1
  - contourpy=1.3.1=py312h68727a3_0
  - cpp-expected=1.1.0=hf52228f_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - distro=1.9.0=pyhd8ed1ab_1
  - double-conversion=3.3.0=h59595ed_0
  - eigen=3.4.0=h00ab1b0_0
  - eigenpy=3.10.1=np20py312hf621b31_0
  - elfutils=0.191=h924a536_0
  - etils=1.10.0=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=7.1.0=gpl_h099772d_709
  - filelock=3.17.0=pyhd8ed1ab_0
  - fmt=11.0.2=h434a139_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.4=py312h178313f_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozendict=2.4.6=py312h66e93f0_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gdbm=1.18=h0a1914f_2
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glfw=3.4=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.8=h2d3e045_0
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=10.2.0=h4bba637_0
  - hdf5=1.14.4=nompi_h2d575fe_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - hpp-fcl=3.0.0=pyhd3e5650_4
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipopt=3.14.17=h59d4785_0
  - jasper=4.2.4=h536e39c_0
  - jinja2=3.1.5=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h7900ff3_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.20.2=h84d6215_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.7=hadbb8c3_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=hba53ac1_1
  - libblas=3.9.0=26_linux64_openblas
  - libblasfeo=0.1.4.1=had105d5_301
  - libboost=1.86.0=hb8260a3_2
  - libboost-devel=1.86.0=h1a2810e_2
  - libboost-headers=1.86.0=ha770c72_2
  - libboost-python=1.86.0=py312hc39e661_2
  - libboost-python-devel=1.86.0=py312h9cebb41_2
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=26_linux64_openblas
  - libccd-double=2.1=h59595ed_3
  - libclang-cpp19.1=19.1.7=default_hb5137d0_0
  - libclang13=19.1.7=default_h9c6a7e4_0
  - libcoal=3.0.0=ha55d5d9_5
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libfatrop=0.0.4=h5888daf_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libgz-cmake3=3.5.3=hac33072_0
  - libgz-math7=7.5.1=h5888daf_2
  - libgz-tools2=2.0.1=h17585e0_0
  - libgz-utils2=2.2.0=h5888daf_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=26_linux64_openblas
  - liblapacke=3.9.0=26_linux64_openblas
  - liblief=0.14.1=h5888daf_2
  - libllvm19=19.1.7=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libmamba=2.0.5=h49b8a8d_1
  - libmambapy=2.0.5=py312hbaee817_1
  - libmicrohttpd=1.0.1=hbc5bc17_1
  - libmujoco=3.2.7=h1419bf0_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopencv=4.10.0=qt6_py312h02963e2_615
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2024.6.0=hac27bb2_3
  - libopenvino-auto-batch-plugin=2024.6.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2024.6.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2024.6.0=h3f63f65_3
  - libopenvino-intel-cpu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-intel-gpu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-intel-npu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-ir-frontend=2024.6.0=h3f63f65_3
  - libopenvino-onnx-frontend=2024.6.0=h6363af5_3
  - libopenvino-paddle-frontend=2024.6.0=h6363af5_3
  - libopenvino-pytorch-frontend=2024.6.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2024.6.0=h630ec5c_3
  - libopenvino-tensorflow-lite-frontend=2024.6.0=h5888daf_3
  - libopus=1.3.1=h7f98852_1
  - libosqp=0.6.3=h5888daf_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.45=h943b412_0
  - libpq=17.2=h3b95a9b_1
  - libprotobuf=5.28.3=h6128344_1
  - libqdldl=0.1.7=hcb278e6_0
  - librsvg=2.58.4=h49af25d_2
  - libscotch=7.0.4=h2fe6a88_5
  - libsdformat14=14.5.0=hb243517_0
  - libsolv=0.7.30=h3509ff9_0
  - libspral=2024.05.08=h2b245be_4
  - libsqlite=3.48.0=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.7.0=hd9ff511_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=hb346dea_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lodepng=20220109=h924138e_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib=3.10.0=py312h7900ff3_0
  - matplotlib-base=3.10.0=py312hd3ec401_0
  - menuinst=2.2.0=py312h7900ff3_0
  - metis=5.1.0=hd0bcaf9_1007
  - more-itertools=10.6.0=pyhd8ed1ab_0
  - mujoco=3.2.7=h78bf25f_0
  - mujoco-python=3.2.7=py312h5a0582c_0
  - mujoco-samples=3.2.7=h5888daf_0
  - mujoco-simulate=3.2.7=h5888daf_0
  - mumps-include=5.7.3=ha770c72_6
  - mumps-seq=5.7.3=h27a6a8b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - nlohmann_json=3.11.3=he02047a_1
  - numpy=2.2.2=py312h72c5963_0
  - ocl-icd=2.3.2=hb9d3cd8_2
  - octomap=1.10.0=h84d6215_0
  - opencl-headers=2024.10.24=h5888daf_0
  - opencv=4.10.0=qt6_py312h8cbcb32_615
  - openexr=3.3.2=h6326327_1
  - openh264=2.5.0=hf92e6e3_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.0=h7b32b05_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.2=pyhd8ed1ab_2
  - pango=1.56.1=h861ebed_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pcre2=10.44=hba22ea6_2
  - pillow=11.1.0=py312h80c1187_0
  - pinocchio=3.3.1=py312h91a64d0_1
  - pip=24.2=py312h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pkginfo=1.12.0=pyhd8ed1ab_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - proxsuite=0.6.7=py312h68727a3_2
  - psutil=6.1.1=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - py-lief=0.14.1=py312h2ec8cdc_2
  - py-opencv=4.10.0=qt6_py312he3389d8_615
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h66e93f0_2
  - pycparser=2.22=pyh29332c3_1
  - pyglfw=2.8.0=pyha770c72_1
  - pyopengl=3.1.6=pyhd8ed1ab_2
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyside6=6.8.1=py312h91f0f75_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-libarchive-c=5.1=py312h7900ff3_1
  - python_abi=3.12=5_cp312
  - pytz=2024.2=pyhd8ed1ab_1
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - qhull-static=2020.2=h434a139_5
  - qt6-main=6.8.1=h588cce1_2
  - readline=8.2=h5eee18b_0
  - referencing=0.36.1=pyhd8ed1ab_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=pyhd8ed1ab_1
  - ripgrep=14.1.1=h8fae777_0
  - robot_descriptions=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.22.3=py312h12e396e_0
  - ruamel.yaml=0.18.10=py312h66e93f0_0
  - ruamel.yaml.clib=0.2.8=py312h66e93f0_1
  - ruby=3.2.2=h983345b_1
  - scipy=1.15.1=py312h180e4f1_0
  - setuptools=75.1.0=py312h06a4308_0
  - simde=0.8.2=h84d6215_0
  - simdjson=3.11.6=h84d6215_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.15.0=h10c9db5_0
  - sqlite=3.32.3=hcee41ef_1
  - svt-av1=2.3.0=h5888daf_0
  - tbb=2022.0.0=hceb3a55_0
  - tinyxml2=10.0.0=h59595ed_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py312h66e93f0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.0=pyhd8ed1ab_0
  - typeguard=4.4.1=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urdfdom=4.0.1=h7fd8c06_0
  - urdfdom_headers=1.1.2=h84d6215_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wheel=0.44.0=py312h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - future-fstrings==1.2.0